version: '3.4'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - docker/postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5433:80
    env_file:
      - docker/pgadmin.env
    depends_on:
      - db
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    
